### ISSUE TITLE
The LeechProtection Xtra still lacks a documentation

### ISSUE THREAD

**Issue by antoniu200** [tomysshadow/LeechProtectionRemovalHelp-Xtra#2]
Hi! I don't mean to bother you, but I've just started (again) working on archiving older Shockwave Player games and I'd like to use your Xtra and make a tutorial at some point regarding playing these older games. But I'm not sure how I can make use of your Xtra. Do I need to use Director to make a Movie that launches another .dcr file by using your functions?

Any help (even if brief) is appreciated.

**Comment by tomysshadow** [comment]
Hi antoniu200,

The reason LeechProtectionRemovalHelp never really got any further documentation is that Flashpoint (specifically SPR) makes it somewhat obsolete. You should follow the instructions to curate Shockwave games using Flashpoint Core. It's explained in this tutorial video - it's old, so some of the instructions are dated, but the majority of it still works the same.

https://www.youtube.com/watch?v=QA9fbL4YplM&feature=youtu.be

**Comment by antoniu200** [comment]
Thanks for the link, I'll check that out.

Also, I want to ask you one more thing. Since Flash Player is going to be phased out in the 31st of December 2020, is there any way to bypass the Flash Player checks that prevent the use of .swf files outside of the original site (e.g.: Railroad Rampage can only be played if launched from Miniclip, nowhere else)?

**Comment by tomysshadow** [comment]
This is the problem that most of the Flashpoint software is purposely created to solve automatically, the Redirector in particular. Beyond that, though, you can use JPEXS to edit the sitelock out of the file manually.

**Comment by antoniu200** [comment]
Yeah, editing them manually would be the best option, as I'd like these games to **just work**, no matter the environment they're launched in.

As for Shockwave games, I hope a "deprotector and decompiler" comes around at some point, as I'd like to remove those checks manually from these too.

Thanks a lot! I'll close the issue.
